pygments: true

permalink: /blog/:categories/:title.html

title: &#29579;&#26199; | Han Wang
url: http://pddds.com
author: Han Wang
email: ""

nav:
    - name: home
      url: /
    - name: home
      url: /about.html
    - name: blog
      url: /blog.html

#googleanalytics: ""

exclude: README.md
